Hw1
Minkerr/Tinkoff_Backend_Course pull request #3
Opened 2023-10-07 21:10 UTC by Minkerr

2023-10-08 14:38 UTC, Stasik371 commented
В целом красава)

2023-10-08 15:12 UTC, Minkerr commented
> В целом красава)

Добрый день! Спасибо. Я не нашёл комментариев, по поводу того, что нужно исправить?

2023-10-08 15:44 UTC, Stasik371 requested changes

2023-10-08 15:44 UTC, Stasik371 commented on src/main/java/edu/hw1/Task7.java
> +    public static int rotateRight(int n, int shift) {
Лайк) Прикольно придумал

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    @Test
Давай стараться придерживаться ААА или GWT. Про это можно почитать снизу)

https://habr.com/ru/articles/507594/

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +    void test1() {
Чтобы не писать циферки предлагаю ввести такую договоренность)

НазваниеМетода_ShouldЧто-тоДелать

Например здесь

minutesToSeconds_shouldConvertIfTimeIsOneMinute

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
> +        int expected = -1;
Давай больше тестов на невалидные данные) Можно написать на символы в строке или что-нибудь такое. И null давай проверим) На дурака в общем)

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task3Test.java
> +    void test4() {
Давай тесты на пустые массивы) и на null)

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +        assertTrue(Task5.isPalindromeDescendant(11211230));
Мало строк это круто, но не в этом случае) хочется читать код сверху вниз, а не справа-налево. Тут еще маленький пример, но может быть 
![image](https://github.com/Minkerr/Tinkoff_Backend_Course/assets/90406808/3fcb6cbd-c3ae-4c75-b8b1-a10356c8bfe0)
 что-то такое)

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +        assertTrue(Task5.isPalindromeDescendant(13001120));
А еще не очень понятно, что этот тест проверяет... Как-будто в данном случае можно комментом дописать путь числа)

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task5Test.java
> +        assertFalse(Task5.isPalindromeDescendant(145));
А еще давай тестиков на 1 цифру)

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task6Test.java
> +        assertEquals(3, Task6.countK(3524, 0));
Тоже бы комментом дописать путь числа от исходного состояния до К. А еще нужно проверка на 1000 и число с 4 одинаковыми цифрами) Такое не должно проходить

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task7Test.java
> +        assertEquals(6, Task7.rotateLeft(17, 2));
Можно дописать тест на случай, когда сдвиг должен привести число в исходное состояние. 

Типо 1000 rotateLeft(4) = 1000

А еще на тот случай, когда у нас число не меняется) например 11 всегда должен оставаться 11

2023-10-08 15:44 UTC, Stasik371 commented on src/test/java/edu/hw1/Task8Test.java
> +        assertFalse(Task8.knightBoardCapture(board));
В целом, можно докинуть тест на: 
нет коней, все кони. Но это пожеланию, должно работать норм)

2023-10-08 15:44 UTC, Stasik371 commented
> > В целом красава)
> 
> Добрый день! Спасибо. Я не нашёл комментариев по поводу того, что нужно исправить. Подскажите, пожалуйста куда смотреть.

Забыл на кнопочку нажать) Теперь вроде появилось

2023-10-08 17:41 UTC, Minkerr commented
Добавил всякие краевые тесты и тесты с некорректными данными.

2023-10-10 19:39 UTC, Stasik371 commented
> Добавил всякие краевые тесты и тесты с некорректными данными. Переименовал названия тестов Про ААА почитал. Как я понял, это к тому же замечанию про одностроки, что нужно тесты оформлять последовательно

В следующий раз переотправляй ответ на задание, либо пиши мне в тг, а то я вижу уведомления только через едушку) @stasik371

2023-10-10 19:43 UTC, Stasik371 commented on src/test/java/edu/hw1/Task1Test.java
>          assertThat(given).isEqualTo(expected);
Это немного не то, вот пример, как надо)
```
//arrange
int expected = 60;
String oneMinute = "01:00"

//act
int actual = Task1.minutesToSeconds(oneMinute);

//assert
assertThat(actual).isEqualTo(expected);
```

Иногда можно упрощать,  комментарии не обязательны, но желательны) actual значение можно не объявлять, а писать сразу в assert

Будем круто, если перепишешь все под стандарт, он намного легче читается) Да и лучше к хорошему сразу привыкать) А комменты скопировать не так долго

2023-10-10 19:46 UTC, Stasik371 commented
Лайк!
![image](https://github.com/Minkerr/Tinkoff_Backend_Course/assets/90406808/607ee6e2-bb0a-4927-9ddd-8c9a01d833fb)

2023-10-13 17:40 UTC, merged